
mc_autocomplete:
    path: autocomplete/{type}
    defaults:
        _controller: AutocompleteBundle:Autocomplete:find
        query: ~
        limit: 30
        page: 1
    requirements:
        limit: \d+
        page: \d+
