services:

    autocomplete.form_type:
        class: MakinaCorpus\AutocompleteBundle\Form\Type\TextAutocompleteType
        arguments: ["@autocomplete.source_registry"]
        tags: [{name: form.type}]

    autocomplete.source_registry:
        class: MakinaCorpus\AutocompleteBundle\Autocomplete\AutocompleteSourceRegistry
        arguments: ["@service_container", "@router"]

    MakinaCorpus\AutocompleteBundle\Autocomplete\AutocompleteSourceRegistry:
        public: true
        alias: autocomplete.source_registry

    # This is a sample using Drupal 8 entity as autocomplete source, please
    # do not use it as-is but as a code sample for implementing your own.
    #
    # autocomplete.node_page_source:
    #     class: MakinaCorpus\AutocompleteBundle\Autocomplete\NodePageAutocompleteSource
    #     arguments: ["@entity.manager", "@database"]
    #     tags: [{name: autocomplete.source}]
