
makinacorpus_autocomplete.find:
    path: autocomplete/{type}
    controller: MakinaCorpus\Autocomplete\Bundle\Controller\AutcompleteController::find
    defaults:
        query: ~
        limit: 30
        page: 1
    requirements:
        limit: \d+
        page: \d+
