services:

    _defaults:
        public: false

    MakinaCorpus\Autocomplete\Bundle\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MakinaCorpus\Autocomplete\Bundle\Form\Type\TextAutocompleteType:
        autowire: true
        tags: [{name: form.type}]

    MakinaCorpus\Autocomplete\Bundle\DependencyInjection\SourceRegistry:
        arguments: ["@service_container", "@router"]
