services:

    autocomplete.form_type:
        class: MakinaCorpus\Autocomplete\Bundle\Form\Type\TextAutocompleteType
        arguments: ["@autocomplete.source_registry"]
        tags: [{name: form.type}]

    autocomplete.source_registry:
        class: MakinaCorpus\AutocompleteBundle\Autocomplete\SourceRegistry
        arguments: ["@service_container", "@router"]

    MakinaCorpus\Autocomplete\Bundle\DependencyInjection\SourceRegistry:
        public: true
        alias: autocomplete.source_registry
